# Generated by Django 4.2.5 on 2023-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_articles_content_alter_articles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
    ]
